Tests & fixes
 - Fix for return values when errors present
 - Tests:
   - Updated return error syntax to more verbose about errors
   - Added new test for handling additions to existing permission stanzas

diff --git a/manage-sudoers b/manage-sudoers
--- a/manage-sudoers
+++ b/manage-sudoers
@@ -713,6 +713,7 @@ make_change_add()
   if [ "${permissions}" == "" ]; then
     local mode=($(echo "${key}"|awk '{print $1}'))
   else
+    local perm=$(echo "${search}"|awk -F= '{print $1}'|awk '{print $2}')
     local mode="${key_orig}"
   fi
 
@@ -734,7 +735,11 @@ make_change_add()
   if [ "${permissions}" == "" ]; then
     replacement="${mode} ${key_orig} = $(echo "${accts[@]}"|tr ' ' ',')"
   else
-    replacement="${mode} $(echo "${accts[@]}"|tr ' ' ',')"
+    if [ ${add} -eq 1 ]; then
+      replacement="${mode} $(echo "${accts[@]}"|tr ' ' ',')"
+    else
+      replacement="${mode} ${perm}=$(echo "${accts[@]}"|tr ' ' ',')"
+    fi
   fi
 
   # Make the change
@@ -900,6 +905,23 @@ main()
   local info=("$(${subroutine})")
   local ret=$?
 
+  # Handle errors return
+  if [[ ${ret} -eq 1 ]] || [[ "${info[@]}" =~ ERROR ]]; then
+
+    # Header for errors
+    echo "${prog}: Errors found"
+
+    # Convert to an array
+    IFS='-' read -a iobj <<< "${info}"
+
+    # Iterate error messages
+    for err in "${iobj[@]}" ; do
+      echo "  ${err}"
+    done
+
+    exit 1
+  fi
+
   # Be verbose if asked
   if [ "${verbose}" == 1 ] ; then
 
@@ -918,20 +940,6 @@ main()
     done
 
     echo ""
-  fi
-
-  # Handle return
-  if [ "${ret}" != 0 ] ; then
-
-    # Header for errors
-    echo "${prog}: Errors found"
-
-    # Iterate error messages
-    for err in "${errors[@]}" ; do
-      echo "  ${err}"
-    done
-
-    exit 1
   fi
 
   # All checks passed
@@ -1058,15 +1066,15 @@ robot()
     # Verify file copied, (read-only DMZ filesystems)
     if [ $? -eq 1 ]; then
       errors+=("ERROR: Could not restore ${file} from ${tmp_file}-")
-      echo "${errors[@]}" && return
+      echo "${errors[@]}" && return 1
     fi
   fi
 
   # Perform validation if pattern exists in file
 
   # Return errors
-  if [ "${#errors[@]}" != 0 ] ; then
-    echo "${errors[@]}" && return
+  if [[ "${#errors[@]}" != 0 ]] || [[ ${result} -ne 0 ]]; then
+    echo "${errors[@]}" && return 1
   fi
 
   # Expose information array
diff --git a/test/lib/tests/perms-add b/test/lib/tests/perms-add
--- a/test/lib/tests/perms-add
+++ b/test/lib/tests/perms-add
@@ -40,7 +40,7 @@ if [ ${#permissions[@]} -gt 0 ]; then
     # Suppress output but handle return code
     bogus=$(${sudoadm} -Vf ${name} -aP ${data} "${permissions[${data}]}")
     if [ $? -ne 0 ]; then
-      echo "Failed addition of new Permissions" && exit 1
+      echo "Failed addition of new '${data}' Permissions" && exit 1
     fi
 
     # Create a needle to search for
@@ -49,7 +49,7 @@ if [ ${#permissions[@]} -gt 0 ]; then
     # Use ${needle} to create ${haystack} from ${name}
     haystack=$(grep "${needle}" ${name})
     if [ "${haystack}" == "" ]; then
-      echo "Failed validation of new Permissions" && exit 1
+      echo "Failed validation of new '${data}' Permissions" && exit 1
     fi
 
     # Clean up our working file(s)
diff --git a/test/lib/tests/perms-remove-from b/test/lib/tests/perms-remove-from
--- a/test/lib/tests/perms-remove-from
+++ b/test/lib/tests/perms-remove-from
@@ -45,7 +45,7 @@ if [ ${#permissions[@]} -gt 0 ]; then
     # Add an alias so we can remove it
     bogus=$(${sudoadm} -Vf ${name} -aP ${data} "${permissions[${data}]}")
     if [ $? -ne 0 ]; then
-      echo "Failed addition of new Permissions" && exit 1
+      echo "Failed addition of new '${data}' Permissions" && exit 1
     fi
 
     # Create a needle to search for
@@ -54,7 +54,7 @@ if [ ${#permissions[@]} -gt 0 ]; then
     # Use ${needle} to create ${haystack} from ${name}
     haystack=$(grep "${needle}" ${name})
     if [ "${haystack}" == "" ]; then
-      echo "Failed validation of new Permissions" && exit 1
+      echo "Failed validation of new '${data}' Permissions" && exit 1
     fi
 
     # Sleep for .1 seconds to accomodate for race conditions
@@ -72,13 +72,13 @@ if [ ${#permissions[@]} -gt 0 ]; then
     # Now remove the alias ${data}
     bogus=$(${sudoadm} -Vf ${name} -rP ${data} "${item}")
     if [ $? -ne 0 ]; then
-      echo "Failed removal of new Permissions" && exit 1
+      echo "Failed removal of new '${data}' Permissions" && exit 1
     fi
 
     # Use ${item} to create ${haystack} from ${name}
     haystack=$(grep "${item}" ${name})
     if [ "${haystack}" != "" ]; then
-      echo "Failed validation of remvoval of Permissions" && exit 1
+      echo "Failed validation for remvoval of '${data}' Permissions" && exit 1
     fi
 
     # Clean up our working file(s)
diff --git a/test/lib/tests/user-add b/test/lib/tests/user-add
--- a/test/lib/tests/user-add
+++ b/test/lib/tests/user-add
@@ -40,7 +40,7 @@ if [ ${#user_aliases[@]} -gt 0 ]; then
     # Suppress output but handle return code
     bogus=$(${sudoadm} -Vf ${name} -aA ${data} "${user_aliases[${data}]}")
     if [ $? -ne 0 ]; then
-      echo "Failed addition of new User_Alias" && exit 1
+      echo "Failed addition of new '${data}' User_Alias" && exit 1
     fi
 
     # Create a needle to search for
@@ -49,7 +49,7 @@ if [ ${#user_aliases[@]} -gt 0 ]; then
     # Use ${needle} to create ${haystack} from ${name}
     haystack=$(grep "${needle}" ${name})
     if [ "${haystack}" == "" ]; then
-      echo "Failed validation of new User_Alias" && exit 1
+      echo "Failed validation of new '${data}' User_Alias" && exit 1
     fi
 
     # Clean up our working file(s)
diff --git a/test/lib/tests/user-add-to b/test/lib/tests/user-add-to
--- a/test/lib/tests/user-add-to
+++ b/test/lib/tests/user-add-to
@@ -45,7 +45,7 @@ if [ ${#user_aliases[@]} -gt 0 ]; then
     # Add an alias so we can remove it
     bogus=$(${sudoadm} -Vf ${name} -aA ${data} "${user_aliases[${data}]}")
     if [ $? -ne 0 ]; then
-      echo "Failed addition of new User_Alias" && exit 1
+      echo "Failed addition of new '${data}' User_Alias" && exit 1
     fi
 
     # Create a needle to search for
@@ -54,25 +54,25 @@ if [ ${#user_aliases[@]} -gt 0 ]; then
     # Use ${needle} to create ${haystack} from ${name}
     haystack=$(grep "${needle}" ${name})
     if [ "${haystack}" == "" ]; then
-      echo "Failed validation of new User_Alias" && exit 1
+      echo "Failed validation of new '${data}' User_Alias" && exit 1
     fi
 
     # Sleep for .1 seconds to accomodate for race conditions
     sleep .1
 
     # Randomly generate a user to add to the ${data} User_Alias
-    item=$RANDOM
+    item="$(cat /dev/urandom | tr -dc 'a-z0-9' | head -c 8)"
 
     # Now add ${item} the alias ${data}
     bogus=$(${sudoadm} -Vf ${name} -aA ${data} "${item}")
     if [ $? -ne 0 ]; then
-      echo "Failed to add ${item} to ${data} new User_Alias" && exit 1
+      echo "Failed to add '${item}' to '${data}' new User_Alias" && exit 1
     fi
 
     # Use ${item} to create ${haystack} from ${name}
     haystack=$(grep "${item}" ${name})
     if [ "${haystack}" == "" ]; then
-      echo "Failed addition of ${item} to ${data} User_Alias" && exit 1
+      echo "Failed addition of '${item}' in '${data}' User_Alias" && exit 1
     fi
 
     # Clean up our working file(s)
diff --git a/test/lib/tests/user-remove b/test/lib/tests/user-remove
--- a/test/lib/tests/user-remove
+++ b/test/lib/tests/user-remove
@@ -40,7 +40,7 @@ if [ ${#user_aliases[@]} -gt 0 ]; then
     # Add an alias so we can remove it
     bogus=$(${sudoadm} -Vf ${name} -aA ${data} "${user_aliases[${data}]}")
     if [ $? -ne 0 ]; then
-      echo "Failed addition of new User_Alias" && exit 1
+      echo "Failed addition of new '${data}' User_Alias" && exit 1
     fi
 
     # Create a needle to search for
@@ -49,7 +49,7 @@ if [ ${#user_aliases[@]} -gt 0 ]; then
     # Use ${needle} to create ${haystack} from ${name}
     haystack=$(grep "${needle}" ${name})
     if [ "${haystack}" == "" ]; then
-      echo "Failed validation of new User_Alias" && exit 1
+      echo "Failed validation of new '${data}' User_Alias" && exit 1
     fi
 
     # Sleep for .1 seconds to accomodate for race conditions
@@ -58,13 +58,13 @@ if [ ${#user_aliases[@]} -gt 0 ]; then
     # Now remove the alias ${data}
     bogus=$(${sudoadm} -Vf ${name} -rA ${data})
     if [ $? -ne 0 ]; then
-      echo "Failed removal of new User_Alias" && exit 1
+      echo "Failed removal of new '${data}' User_Alias" && exit 1
     fi
 
     # Use ${needle} to create ${haystack} from ${name}
     haystack=$(grep "${needle}" ${name})
     if [ "${haystack}" != "" ]; then
-      echo "Failed validation of remvoval of User_Alias" && exit 1
+      echo "Failed validation for remvoval of '${data}' User_Alias" && exit 1
     fi
 
     # Clean up our working file(s)
