manage-sudoers:
  - Fix for find_sudo() function
  - Fix for make_change_add() regarding permissions stanza
  - Tests: Added test cases for adding, editing, removing User_Alias, Cmnd_Alias
    & permissions stanzas

diff --git a/manage-sudoers b/manage-sudoers
--- a/manage-sudoers
+++ b/manage-sudoers
@@ -422,21 +422,27 @@ find_sudoer()
 {
   local needle="${sudoer}"
 
-  if [[ "${newfile}" -eq 0 ]] && [[ ! -f "${sudoer}" ]]; then
-    info+=("INFO Searching: ${haystack}-")
+  # Make ${sudoer} if it doesn't exist & ${newfile} is true
+  if [[ ${newfile} -eq 1 ]] && [[ ! -f "${sudoer}" ]]; then
+    create_sudoer_file "${sudoer}"
+    echo "${sudoer}" && return 0
+  else
 
-    local haystack=$(find_sudoer_path)
-    needle=$(find "${haystack}" -type f -name "${sudoer}")
-  fi
+    # If ${sudoer} exists no need to search for it
+    if [ -f "${sudoer}" ]; then
+      echo "${sudoer}" && return 0
+    else
 
-  if [ ! -f "${sudoer}" ]; then
-    if [ "${newfile}" -eq 1 ]; then
-      create_sudoer_file "${sudoer}"
-      needle="${needle}"
+      # Search for the filename provided
+      local haystack=$(find_sudoer_path)
+      needle=$(find "${haystack}" -type f -name "$(basename ${sudoer})")
+      if [ -f ${needle} ]; then
+        echo "${needle}" && return 0
+      fi
     fi
   fi
 
-  echo "${needle}"
+  return 1
 }
 
 # Create specified sudoer file
@@ -662,10 +668,11 @@ make_change_add()
   local value="${@:5}"
 
   local add=0
+  local type=0
 
   # If ${key} is empty exit
   if [ "${key}" == "" ]; then
-    errors+=("ERROR: No value found for $(echo "${key}"|awk '{print $1}')-")
+    errors+=("ERROR: Missing argument, empty key-")
     return 1
   fi
 
@@ -675,8 +682,15 @@ make_change_add()
     return 1
   fi
 
-  # Split ${value} into an array
-  IFS=' ' read -a act <<< "${value}"
+  # Determine formatting for ${value}
+  type="$(echo "${value}"|awk '$0 !~ /,/{print 1}')"
+  if [ ${type} -eq 0 ]; then
+
+    # Split ${value} into an array
+    IFS=' ' read -a act <<< "${value}"
+  else
+    act="${value}"
+  fi
 
   # If ${obj[@]} is empty exit
   if [ ${#act[@]} -lt 1 ]; then
@@ -934,18 +948,16 @@ robot()
 {
   # Perform validation of args
 
-  # Was a file specified and does it exist?
-  if [[ ! -f "${sudoer}" ]] && [[ "${newfile}" -eq 1 ]]; then
-    create_sudoer_file "${sudoer}"
-    file="${sudoer}"
-  else
-    # Or find it
-    file=$(find_sudoer)
+  # Get or create supplied sudoer file
+  file=$(find_sudoer)
+  if [ $? -ne 0 ]; then
+    errors+=("ERROR: Could not locate or create file-")
+    echo "${errors[@]}" && return 1
   fi
 
   # Make sure it is valid
   if [ ! -f "${file}" ]; then
-    errors+=("ERROR: Could not locate file (${file})-")
+    errors+=("ERROR: Could not locate file (${file}${sudoer})-")
     echo "${errors[@]}" && return 1
   fi
 
diff --git a/test/lib/tests/cmnd-add b/test/lib/tests/cmnd-add
--- a/test/lib/tests/cmnd-add
+++ b/test/lib/tests/cmnd-add
@@ -1,7 +1,5 @@
 #!/bin/bash
 
-# Add & verify User_Alias stanza
-
 # First arg should be our configuration file path
 config=$([ "$1" != "" ] && echo "$1" || echo "../../assets/config")
 
@@ -17,7 +15,46 @@ if [ ! -f ${config} ]; then
   exit 1
 fi
 
-# Load ${config}
 source ${config}
 
-echo "not complete"
+# Check for 'manage-sudoers'
+if [ ! -f "${sudoadm}" ]; then
+  sudoadm=$(find / -xdev -type f -name manage-sudoers|sort -u|head -1)
+fi
+
+# Check for 'sudoers'
+if [ ! -f "${file}" ]; then
+  file=$(find $(dirname ${config}) -xdev -type f -name sudoers|sort -u|head -1)
+fi
+
+# Ensure ${user_aliases[@]} is > 0
+if [ ${#cmnd_aliases[@]} -gt 0 ]; then
+
+  # Begin iteration of ${cmnd_aliases[@]}
+  for data in ${!cmnd_aliases[@]}; do
+
+    # Make a temporary copy of ${file}
+    name="${tmp_dir}$(basename ${file}).${data}.$RANDOM"
+    cp ${file} ${name}
+
+    # Suppress output but handle return code
+    bogus=$(${sudoadm} -Vf ${name} -aC ${data} "${cmnd_aliases[${data}]}")
+    if [ $? -ne 0 ]; then
+      echo "Failed addition of new Cmnd_Alias" && exit 1
+    fi
+
+    # Create a needle to search for
+    needle="^Cmnd_Alias.*${data}.*$(echo "${cmnd_aliases[${data}]}"|sed -e 's|, |.*|g')"
+
+    # Use ${needle} to create ${haystack} from ${name}
+    haystack=$(grep "${needle}" ${name})
+    if [ "${haystack}" == "" ]; then
+      echo "Failed validation of new Cmnd_Alias" && exit 1
+    fi
+
+    # Clean up our working file(s)
+    rm -f ${name}*
+  done
+fi
+
+echo "Passed"
diff --git a/test/lib/tests/cmnd-add-to b/test/lib/tests/cmnd-add-to
--- a/test/lib/tests/cmnd-add-to
+++ b/test/lib/tests/cmnd-add-to
@@ -27,44 +27,52 @@ if [ ! -f "${file}" ]; then
   file=$(find $(dirname ${config}) -xdev -type f -name sudoers|sort -u|head -1)
 fi
 
-# Ensure ${permissions[@]} is > 0
-if [ ${#permissions[@]} -gt 0 ]; then
+# Ensure ${cmnd_aliases[@]} is > 0
+if [ ${#cmnd_aliases[@]} -gt 0 ]; then
 
-  # Begin iteration of ${permissions[@]}
-  for data in ${!permissions[@]}; do
+  # Begin iteration of ${cmnd_aliases[@]}
+  for data in ${!cmnd_aliases[@]}; do
+
+    # Reset ${items}, ${item} & ${random) to empty
+    items=
+    item=
+    random=
 
     # Make a temporary copy of ${file}
     name="${tmp_dir}$(basename ${file}).${data}.$RANDOM"
     cp ${file} ${name}
 
-    # Add a new permissions stanza so we can remove it
-    bogus=$(${sudoadm} -Vf ${name} -aP ${data} "${permissions[${data}]}")
+    # Add an alias so we can remove it
+    bogus=$(${sudoadm} -Vf ${name} -aC ${data} "${cmnd_aliases[${data}]}")
     if [ $? -ne 0 ]; then
-      echo "Failed addition of new Permissions" && exit 1
+      echo "Failed addition of new Cmnd_Alias" && exit 1
     fi
 
     # Create a needle to search for
-    needle="^${data}.*$(echo "${permissions[${data}]}"|sed -e 's|, |.*|g')"
+    needle="^Cmnd_Alias.*${data}.*$(echo "${cmnd_aliases[${data}]}"|sed -e 's|, |.*|g')"
 
     # Use ${needle} to create ${haystack} from ${name}
     haystack=$(grep "${needle}" ${name})
     if [ "${haystack}" == "" ]; then
-      echo "Failed validation of new Permissions" && exit 1
+      echo "Failed validation of new Cmnd_Alias" && exit 1
     fi
 
     # Sleep for .1 seconds to accomodate for race conditions
     sleep .1
 
-    # Now remove the Permissions ${data}
-    bogus=$(${sudoadm} -Vf ${name} -rP ${data})
+    # Randomly generate a user to add to the ${data} Cmnd_Alias
+    item="/$RANDOM"
+
+    # Now add ${item} the alias ${data}
+    bogus=$(${sudoadm} -Vf ${name} -aC ${data} "${item}")
     if [ $? -ne 0 ]; then
-      echo "Failed removal of new Permissions" && exit 1
+      echo "Failed to add ${item} to ${data} new Cmnd_Alias" && exit 1
     fi
 
-    # Use ${needle} to create ${haystack} from ${name}
-    haystack=$(grep "${needle}" ${name})
-    if [ "${haystack}" != "" ]; then
-      echo "Failed validation of remvoval of Permissions" && exit 1
+    # Use ${item} to create ${haystack} from ${name}
+    haystack=$(grep "${item}" ${name})
+    if [ "${haystack}" == "" ]; then
+      echo "Failed validation of ${item} to ${data} Cmnd_Alias" && exit 1
     fi
 
     # Clean up our working file(s)
diff --git a/test/lib/tests/cmnd-remove-from b/test/lib/tests/cmnd-remove-from
--- a/test/lib/tests/cmnd-remove-from
+++ b/test/lib/tests/cmnd-remove-from
@@ -17,4 +17,73 @@ fi
 
 source ${config}
 
-echo "not complete"
+# Check for 'manage-sudoers'
+if [ ! -f "${sudoadm}" ]; then
+  sudoadm=$(find / -xdev -type f -name manage-sudoers|sort -u|head -1)
+fi
+
+# Check for 'sudoers'
+if [ ! -f "${file}" ]; then
+  file=$(find $(dirname ${config}) -xdev -type f -name sudoers|sort -u|head -1)
+fi
+
+# Ensure ${cmnd_aliases[@]} is > 0
+if [ ${#cmnd_aliases[@]} -gt 0 ]; then
+
+  # Begin iteration of ${cmnd_aliases[@]}
+  for data in ${!cmnd_aliases[@]}; do
+
+    # Reset ${items}, ${item} & ${random) to empty
+    items=
+    item=
+    random=
+
+    # Make a temporary copy of ${file}
+    name="${tmp_dir}$(basename ${file}).${data}.$RANDOM"
+    cp ${file} ${name}
+
+    # Add an alias so we can remove it
+    bogus=$(${sudoadm} -Vf ${name} -aC ${data} "${cmnd_aliases[${data}]}")
+    if [ $? -ne 0 ]; then
+      echo "Failed addition of new Cmnd_Alias" && exit 1
+    fi
+
+    # Create a needle to search for
+    needle="^Cmnd_Alias.*${data}.*$(echo "${cmnd_aliases[${data}]}"|sed -e 's|, |.*|g')"
+
+    # Use ${needle} to create ${haystack} from ${name}
+    haystack=$(grep "${needle}" ${name})
+    if [ "${haystack}" == "" ]; then
+      echo "Failed validation of new Cmnd_Alias" && exit 1
+    fi
+
+    # Sleep for .1 seconds to accomodate for race conditions
+    sleep .1
+
+    # Generate a random number for this iteration
+    random=$(shuf -i 0-$(expr ${#items[@]} - 1) -n 1)
+
+    # Generate an array from ${cmnd_aliases[${data}]}
+    IFS=',' read -a items <<< "$(echo "${cmnd_aliases[${data}]}")"
+
+    # Randomly pick an element from ${cmnd_aliases[${data}]} to remove
+    item=$(echo "${items[${random}]}")
+
+    # Now remove the alias ${data}
+    bogus=$(${sudoadm} -Vf ${name} -rC ${data} "${item}")
+    if [ $? -ne 0 ]; then
+      echo "Failed removal of new Cmnd_Alias" && exit 1
+    fi
+
+    # Use ${item} to create ${haystack} from ${name}
+    haystack=$(grep "${item}" ${name})
+    if [ "${haystack}" != "" ]; then
+      echo "Failed validation of remvoval of Cmnd_Alias" && exit 1
+    fi
+
+    # Clean up our working file(s)
+    rm -f ${name}*
+  done
+fi
+
+echo "Passed"
diff --git a/test/lib/tests/perms-add-to b/test/lib/tests/perms-add-to
--- a/test/lib/tests/perms-add-to
+++ b/test/lib/tests/perms-add-to
@@ -33,11 +33,16 @@ if [ ${#permissions[@]} -gt 0 ]; then
   # Begin iteration of ${permissions[@]}
   for data in ${!permissions[@]}; do
 
+    # Reset ${items}, ${item} & ${random) to empty
+    items=
+    item=
+    random=
+
     # Make a temporary copy of ${file}
     name="${tmp_dir}$(basename ${file}).${data}.$RANDOM"
     cp ${file} ${name}
 
-    # Add a new permissions stanza so we can remove it
+    # Add an alias so we can remove it
     bogus=$(${sudoadm} -Vf ${name} -aP ${data} "${permissions[${data}]}")
     if [ $? -ne 0 ]; then
       echo "Failed addition of new Permissions" && exit 1
@@ -55,16 +60,21 @@ if [ ${#permissions[@]} -gt 0 ]; then
     # Sleep for .1 seconds to accomodate for race conditions
     sleep .1
 
-    # Now remove the Permissions ${data}
-    bogus=$(${sudoadm} -Vf ${name} -rP ${data})
+    # Randomly generate a user to add to the ${data} Permissions
+    item="/$RANDOM"
+
+    # Now add ${item} the alias ${data}
+    bogus=$(${sudoadm} -Vf ${name} -aP ${data} "${item}")
+echo "${bogus}"
     if [ $? -ne 0 ]; then
-      echo "Failed removal of new Permissions" && exit 1
+      echo "Failed to add ${item} to ${data} new Permissions" && exit 1
     fi
 
-    # Use ${needle} to create ${haystack} from ${name}
-    haystack=$(grep "${needle}" ${name})
-    if [ "${haystack}" != "" ]; then
-      echo "Failed validation of remvoval of Permissions" && exit 1
+    # Use ${item} to create ${haystack} from ${name}
+    haystack=$(grep "${item}" ${name})
+echo "${haystack}"
+    if [ "${haystack}" == "" ]; then
+      echo "Failed addition of ${item} to ${data} Permissions" && exit 1
     fi
 
     # Clean up our working file(s)
