Added additional output for test cases & working on filters

diff --git a/test/lib/tests/cmnd-add-to b/test/lib/tests/cmnd-add-to
--- a/test/lib/tests/cmnd-add-to
+++ b/test/lib/tests/cmnd-add-to
@@ -47,9 +47,9 @@ if [ ${#cmnd_aliases[@]} -gt 0 ]; then
 
     # Add an alias so we can remove it
     bogus=$(${sudoadm} -Vf ${name} -aC ${data} "${cmnd_aliases[${data}]}")
-    echo "${bogus}"
     if [ $? -ne 0 ]; then
-      echo "Failed addition of new '${data}' Cmnd_Alias" && exit 1
+      echo "Failed addition of new '${data}' Cmnd_Alias"
+      echo "${bogus}" && exit 1
     fi
 
     # Create a needle to search for
@@ -58,7 +58,8 @@ if [ ${#cmnd_aliases[@]} -gt 0 ]; then
     # Use ${needle} to create ${haystack} from ${name}
     haystack=$(grep "${needle}" ${name})
     if [ "${haystack}" == "" ]; then
-      echo "Failed validation of new '${data}' Cmnd_Alias" && exit 1
+      echo "Failed validation of new '${data}' Cmnd_Alias"
+      echo "${bogus}" && exit 1
     fi
 
     # Sleep for .1 seconds to accomodate for race conditions
@@ -70,13 +71,15 @@ if [ ${#cmnd_aliases[@]} -gt 0 ]; then
     # Now add ${item} the alias ${data}
     bogus=$(${sudoadm} -Vf ${name} -aC ${data} "${item}")
     if [ $? -ne 0 ]; then
-      echo "Failed to add '${item}' to '${data}' new Cmnd_Alias" && exit 1
+      echo "Failed to add '${item}' to '${data}' new Cmnd_Alias"
+      echo "${bogus}" && exit 1
     fi
 
     # Use ${item} to create ${haystack} from ${name}
     haystack=$(grep "${item}" ${name})
     if [ "${haystack}" == "" ]; then
-      echo "Failed validation of '${item}' in '${data}' Cmnd_Alias" && exit 1
+      echo "Failed validation of '${item}' in '${data}' Cmnd_Alias"
+      echo "${bogus}" && exit 1
     fi
 
     # Clean up our working file(s)
diff --git a/test/lib/tests/cmnd-remove b/test/lib/tests/cmnd-remove
--- a/test/lib/tests/cmnd-remove
+++ b/test/lib/tests/cmnd-remove
@@ -43,7 +43,8 @@ if [ ${#cmnd_aliases[@]} -gt 0 ]; then
     # Add an alias so we can remove it
     bogus=$(${sudoadm} -Vf ${name} -aC ${data} "${cmnd_aliases[${data}]}")
     if [ $? -ne 0 ]; then
-      echo "Failed addition of new '${data}' Cmnd_Alias" && exit 1
+      echo "Failed addition of new '${data}' Cmnd_Alias"
+      echo "${bogus}" && exit 1
     fi
 
     # Create a needle to search for
@@ -52,7 +53,8 @@ if [ ${#cmnd_aliases[@]} -gt 0 ]; then
     # Use ${needle} to create ${haystack} from ${name}
     haystack=$(grep "${needle}" ${name})
     if [ "${haystack}" == "" ]; then
-      echo "Failed validation of new '${data}' Cmnd_Alias" && exit 1
+      echo "Failed validation of new '${data}' Cmnd_Alias"
+      echo "${bogus}" && exit 1
     fi
 
     # Sleep for .1 seconds to accomodate for race conditions
@@ -61,13 +63,15 @@ if [ ${#cmnd_aliases[@]} -gt 0 ]; then
     # Now remove the alias ${data}
     bogus=$(${sudoadm} -Vf ${name} -rC ${data})
     if [ $? -ne 0 ]; then
-      echo "Failed removal of '${data}' Cmnd_Alias" && exit 1
+      echo "Failed removal of '${data}' Cmnd_Alias"
+      echo "${bogus}" && exit 1
     fi
 
     # Use ${needle} to create ${haystack} from ${name}
     haystack=$(grep "${needle}" ${name})
     if [ "${haystack}" != "" ]; then
-      echo "Failed validation for remvoval of '${data}' Cmnd_Alias" && exit 1
+      echo "Failed validation for remvoval of '${data}' Cmnd_Alias"
+      echo "${bogus}" && exit 1
     fi
 
     # Clean up our working file(s)
diff --git a/test/lib/tests/cmnd-remove-from b/test/lib/tests/cmnd-remove-from
--- a/test/lib/tests/cmnd-remove-from
+++ b/test/lib/tests/cmnd-remove-from
@@ -48,7 +48,8 @@ if [ ${#cmnd_aliases[@]} -gt 0 ]; then
     # Add an alias so we can remove it
     bogus=$(${sudoadm} -Vf ${name} -aC ${data} "${cmnd_aliases[${data}]}")
     if [ $? -ne 0 ]; then
-      echo "Failed addition of new '${data}' Cmnd_Alias" && exit 1
+      echo "Failed addition of new '${data}' Cmnd_Alias"
+      echo "${bogus}" && exit 1
     fi
 
     # Create a needle to search for
@@ -58,7 +59,8 @@ if [ ${#cmnd_aliases[@]} -gt 0 ]; then
     haystack=$(grep "${needle}" ${name})
 
     if [ "${haystack}" == "" ]; then
-      echo "Failed validation of new '${data}' Cmnd_Alias" && exit 1
+      echo "Failed validation of new '${data}' Cmnd_Alias"
+      echo "${bogus}" && exit 1
     fi
 
     # Sleep for .1 seconds to accomodate for race conditions
@@ -83,13 +85,15 @@ if [ ${#cmnd_aliases[@]} -gt 0 ]; then
     # Now remove the alias ${data}
     bogus=$(${sudoadm} -Vf ${name} -rC ${data} "${item}")
     if [ $? -ne 0 ]; then
-      echo "Failed removal of new '${data}' Cmnd_Alias" && exit 1
+      echo "Failed removal of new '${data}' Cmnd_Alias"
+      echo "${bogus}" && exit 1
     fi
 
     # Use ${item} to create ${haystack} from ${name}
     haystack=$(grep "${item}" ${name})
     if [ "${haystack}" != "" ]; then
-      echo "Failed validation for remvoval of '${item}' from the '${data}' Cmnd_Alias" && exit 1
+      echo "Failed validation for remvoval of '${item}' from the '${data}' Cmnd_Alias"
+      echo "${bogus}" && exit 1
     fi
 
     # Clean up our working file(s)
diff --git a/test/lib/tests/host-add-to b/test/lib/tests/host-add-to
--- a/test/lib/tests/host-add-to
+++ b/test/lib/tests/host-add-to
@@ -48,7 +48,8 @@ if [ ${#host_aliases[@]} -gt 0 ]; then
     # Add an alias so we can remove it
     bogus=$(${sudoadm} -Vf ${name} -aH ${data} "${host_aliases[${data}]}")
     if [ $? -ne 0 ]; then
-      echo "Failed addition of new '${data}' Host_Alias" && exit 1
+      echo "Failed addition of new '${data}' Host_Alias"
+      echo "${bogus}" && exit 1
     fi
 
     # Create a needle to search for
@@ -57,7 +58,8 @@ if [ ${#host_aliases[@]} -gt 0 ]; then
     # Use ${needle} to create ${haystack} from ${name}
     haystack=$(grep "${needle}" ${name})
     if [ "${haystack}" == "" ]; then
-      echo "Failed validation of new '${data}' Host_Alias" && exit 1
+      echo "Failed validation of new '${data}' Host_Alias"
+      echo "${bogus}" && exit 1
     fi
 
     # Sleep for .1 seconds to accomodate for race conditions
@@ -69,13 +71,15 @@ if [ ${#host_aliases[@]} -gt 0 ]; then
     # Now add ${item} the alias ${data}
     bogus=$(${sudoadm} -Vf ${name} -aH ${data} "${item}")
     if [ $? -ne 0 ]; then
-      echo "Failed to add '${item}' to '${data}' new Host_Alias" && exit 1
+      echo "Failed to add '${item}' to '${data}' new Host_Alias"
+      echo "${bogus}" && exit 1
     fi
 
     # Use ${item} to create ${haystack} from ${name}
     haystack=$(grep "${item}" ${name})
     if [ "${haystack}" == "" ]; then
-      echo "Failed addition of '${item}' in '${data}' Host_Alias" && exit 1
+      echo "Failed addition of '${item}' in '${data}' Host_Alias"
+      echo "${bogus}" && exit 1
     fi
 
     # Clean up our working file(s)
diff --git a/test/lib/tests/perms-add-to b/test/lib/tests/perms-add-to
--- a/test/lib/tests/perms-add-to
+++ b/test/lib/tests/perms-add-to
@@ -48,7 +48,8 @@ if [ ${#permissions[@]} -gt 0 ]; then
     # Add an alias so we can remove it
     bogus=$(${sudoadm} -Vf ${name} -aP ${data} "${permissions[${data}]}")
     if [ $? -ne 0 ]; then
-      echo "Failed addition of new '${data}' Permissions" && exit 1
+      echo "Failed addition of new '${data}' Permissions"
+      echo "${bogus}" && exit 1
     fi
 
     # Create a needle to search for
@@ -57,7 +58,8 @@ if [ ${#permissions[@]} -gt 0 ]; then
     # Use ${needle} to create ${haystack} from ${name}
     haystack=$(grep "${needle}" ${name})
     if [ "${haystack}" == "" ]; then
-      echo "Failed validation of new '${data}' Permissions" && exit 1
+      echo "Failed validation of new '${data}' Permissions"
+      echo "${bogus}" && exit 1
     fi
 
     # Sleep for .1 seconds to accomodate for race conditions
@@ -68,14 +70,17 @@ if [ ${#permissions[@]} -gt 0 ]; then
 
     # Now add ${item} the alias ${data}
     bogus=$(${sudoadm} -Vf ${name} -aP ${data} "${item}")
+echo "${bogus}"
     if [ $? -ne 0 ]; then
-      echo "Failed to add '${item}' to '${data}' new Permissions" && exit 1
+      echo "Failed to add '${item}' to '${data}' new Permissions"
+      echo "${bogus}" && exit 1
     fi
 
     # Use ${item} to create ${haystack} from ${name}
     haystack=$(grep "${item}" ${name})
     if [ "${haystack}" == "" ]; then
-      echo "Failed addition of '${item}' in '${data}' Permissions" && exit 1
+      echo "Failed addition of '${item}' in '${data}' Permissions"
+      echo "${bogus}" && exit 1
     fi
 
     # Clean up our working file(s)
diff --git a/test/lib/tests/perms-remove b/test/lib/tests/perms-remove
--- a/test/lib/tests/perms-remove
+++ b/test/lib/tests/perms-remove
@@ -43,7 +43,8 @@ if [ ${#permissions[@]} -gt 0 ]; then
     # Add a new permissions stanza so we can remove it
     bogus=$(${sudoadm} -Vf ${name} -aP ${data} "${permissions[${data}]}")
     if [ $? -ne 0 ]; then
-      echo "Failed addition of new '${data}' Permissions" && exit 1
+      echo "Failed addition of new '${data}' Permissions"
+      echo "${bogus}" && exit 1
     fi
 
     # Create a needle to search for
@@ -52,7 +53,8 @@ if [ ${#permissions[@]} -gt 0 ]; then
     # Use ${needle} to create ${haystack} from ${name}
     haystack=$(grep "${needle}" ${name})
     if [ "${haystack}" == "" ]; then
-      echo "Failed validation of new '${data}' Permissions" && exit 1
+      echo "Failed validation of new '${data}' Permissions"
+      echo "${bogus}" && exit 1
     fi
 
     # Sleep for .1 seconds to accomodate for race conditions
@@ -61,13 +63,15 @@ if [ ${#permissions[@]} -gt 0 ]; then
     # Now remove the Permissions ${data}
     bogus=$(${sudoadm} -Vf ${name} -rP ${data})
     if [ $? -ne 0 ]; then
-      echo "Failed removal of '${data}' Permissions" && exit 1
+      echo "Failed removal of '${data}' Permissions"
+      echo "${bogus}" && exit 1
     fi
 
     # Use ${needle} to create ${haystack} from ${name}
     haystack=$(grep "${needle}" ${name})
     if [ "${haystack}" != "" ]; then
-      echo "Failed validation for remvoval of '${data}' Permissions" && exit 1
+      echo "Failed validation for remvoval of '${data}' Permissions"
+      echo "${bogus}" && exit 1
     fi
 
     # Clean up our working file(s)
diff --git a/test/lib/tests/perms-remove-from b/test/lib/tests/perms-remove-from
--- a/test/lib/tests/perms-remove-from
+++ b/test/lib/tests/perms-remove-from
@@ -48,7 +48,8 @@ if [ ${#permissions[@]} -gt 0 ]; then
     # Add an alias so we can remove it
     bogus=$(${sudoadm} -Vf ${name} -aP ${data} "${permissions[${data}]}")
     if [ $? -ne 0 ]; then
-      echo "Failed addition of new '${data}' Permissions" && exit 1
+      echo "Failed addition of new '${data}' Permissions"
+      echo "${bogus}" && exit 1
     fi
 
     # Create a needle to search for
@@ -57,7 +58,8 @@ if [ ${#permissions[@]} -gt 0 ]; then
     # Use ${needle} to create ${haystack} from ${name}
     haystack=$(grep "${needle}" ${name})
     if [ "${haystack}" == "" ]; then
-      echo "Failed validation of new '${data}' Permissions" && exit 1
+      echo "Failed validation of new '${data}' Permissions"
+      echo "${bogus}" && exit 1
     fi
 
     # Sleep for .1 seconds to accomodate for race conditions
@@ -91,14 +93,17 @@ if [ ${#permissions[@]} -gt 0 ]; then
 
     # Now remove the alias ${data}
     bogus=$(${sudoadm} -Vf ${name} -rP ${data} "${item}")
+echo "${bogus}"
     if [ $? -ne 0 ]; then
-      echo "Failed removal of new '${item}' from the '${data}' Permissions" && exit 1
+      echo "Failed removal of new '${item}' from the '${data}' Permissions"
+      echo "${bogus}" && exit 1
     fi
 
     # Use ${item} to create ${haystack} from ${name}
     haystack=$(grep "${needle}" ${name}|grep "${item}")
     if [ "${haystack}" != "" ]; then
-      echo "Failed validation for remvoval of '${item}' from the '${data}' Permissions" && exit 1
+      echo "Failed validation for remvoval of '${item}' from the '${data}' Permissions"
+      echo "${bogus}" && exit 1
     fi
 
     # Clean up our working file(s)
diff --git a/test/lib/tests/user-add b/test/lib/tests/user-add
--- a/test/lib/tests/user-add
+++ b/test/lib/tests/user-add
@@ -43,7 +43,8 @@ if [ ${#user_aliases[@]} -gt 0 ]; then
     # Suppress output but handle return code
     bogus=$(${sudoadm} -Vf ${name} -aA ${data} "${user_aliases[${data}]}")
     if [ $? -ne 0 ]; then
-      echo "Failed addition of new '${data}' User_Alias" && exit 1
+      echo "Failed addition of new '${data}' User_Alias"
+      echo "${bogus}" && exit 1
     fi
 
     # Create a needle to search for
@@ -52,7 +53,8 @@ if [ ${#user_aliases[@]} -gt 0 ]; then
     # Use ${needle} to create ${haystack} from ${name}
     haystack=$(grep "${needle}" ${name})
     if [ "${haystack}" == "" ]; then
-      echo "Failed validation of new '${data}' User_Alias" && exit 1
+      echo "Failed validation of new '${data}' User_Alias"
+      echo "${bogus}" && exit 1
     fi
 
     # Clean up our working file(s)
diff --git a/test/lib/tests/user-remove b/test/lib/tests/user-remove
--- a/test/lib/tests/user-remove
+++ b/test/lib/tests/user-remove
@@ -43,7 +43,8 @@ if [ ${#user_aliases[@]} -gt 0 ]; then
     # Add an alias so we can remove it
     bogus=$(${sudoadm} -Vf ${name} -aA ${data} "${user_aliases[${data}]}")
     if [ $? -ne 0 ]; then
-      echo "Failed addition of new '${data}' User_Alias" && exit 1
+      echo "Failed addition of new '${data}' User_Alias"
+      echo "${bogus}" && exit 1
     fi
 
     # Create a needle to search for
@@ -52,7 +53,8 @@ if [ ${#user_aliases[@]} -gt 0 ]; then
     # Use ${needle} to create ${haystack} from ${name}
     haystack=$(grep "${needle}" ${name})
     if [ "${haystack}" == "" ]; then
-      echo "Failed validation of new '${data}' User_Alias" && exit 1
+      echo "Failed validation of new '${data}' User_Alias"
+      echo "${bogus}" && exit 1
     fi
 
     # Sleep for .1 seconds to accomodate for race conditions
@@ -61,13 +63,15 @@ if [ ${#user_aliases[@]} -gt 0 ]; then
     # Now remove the alias ${data}
     bogus=$(${sudoadm} -Vf ${name} -rA ${data})
     if [ $? -ne 0 ]; then
-      echo "Failed removal of new '${data}' User_Alias" && exit 1
+      echo "Failed removal of new '${data}' User_Alias"
+      echo "${bogus}" && exit 1
     fi
 
     # Use ${needle} to create ${haystack} from ${name}
     haystack=$(grep "${needle}" ${name})
     if [ "${haystack}" != "" ]; then
-      echo "Failed validation for remvoval of '${data}' User_Alias" && exit 1
+      echo "Failed validation for remvoval of '${data}' User_Alias"
+      echo "${bogus}" && exit 1
     fi
 
     # Clean up our working file(s)
