Test harness fixes   - Path & argument list fixed for harness, groups & individual test cases   - Several test fixes regarding random numbers & sleep tool args

diff --git a/test/lib/tests/host-add b/test/lib/tests/host-add
--- a/test/lib/tests/host-add
+++ b/test/lib/tests/host-add
@@ -30,29 +30,29 @@ if [ ! -f "${file}" ]; then
   file=$(find $(dirname ${config}) -type f -name sudoers|sort -u|head -1)
 fi
 
-# Ensure ${user_aliases[@]} is > 0
-if [ ${#cmnd_aliases[@]} -gt 0 ]; then
+# Ensure ${host_aliases[@]} is > 0
+if [ ${#host_aliases[@]} -gt 0 ]; then
 
-  # Begin iteration of ${cmnd_aliases[@]}
-  for data in ${!cmnd_aliases[@]}; do
+  # Begin iteration of ${host_aliases[@]}
+  for data in ${!host_aliases[@]}; do
 
     # Make a temporary copy of ${file}
     name="${tmp_dir}$(basename ${file}).${data}.$RANDOM"
     cp ${file} ${name}
 
     # Suppress output but handle return code
-    bogus=$(${sudoadm} -Vf ${name} -aC ${data} "${cmnd_aliases[${data}]}")
+    bogus=$(${sudoadm} -Vf ${name} -aH ${data} "${host_aliases[${data}]}")
     if [ $? -ne 0 ]; then
-      echo "Failed addition of new '${data}' Cmnd_Alias" && exit 1
+      echo "Failed addition of new '${data}' Host_Alias" && exit 1
     fi
 
     # Create a needle to search for
-    needle="^Cmnd_Alias.*${data}.*$(echo "${cmnd_aliases[${data}]}"|sed -e 's|, |.*|g')"
+    needle="^Host_Alias.*${data}.*$(echo "${host_aliases[${data}]}"|sed -e 's|, |.*|g')"
 
     # Use ${needle} to create ${haystack} from ${name}
     haystack=$(grep "${needle}" ${name})
     if [ "${haystack}" == "" ]; then
-      echo "Failed validation of new '${data}' Cmnd_Alias" && exit 1
+      echo "Failed validation of new '${data}' Host_Alias" && exit 1
     fi
 
     # Clean up our working file(s)
diff --git a/test/lib/tests/host-remove-from b/test/lib/tests/host-remove-from
--- a/test/lib/tests/host-remove-from
+++ b/test/lib/tests/host-remove-from
@@ -30,11 +30,11 @@ if [ ! -f "${file}" ]; then
   file=$(find $(dirname ${config}) -type f -name sudoers|sort -u|head -1)
 fi
 
-# Ensure ${cmnd_aliases[@]} is > 0
-if [ ${#cmnd_aliases[@]} -gt 0 ]; then
+# Ensure ${host_aliases[@]} is > 0
+if [ ${#host_aliases[@]} -gt 0 ]; then
 
-  # Begin iteration of ${cmnd_aliases[@]}
-  for data in ${!cmnd_aliases[@]}; do
+  # Begin iteration of ${host_aliases[@]}
+  for data in ${!host_aliases[@]}; do
 
     # Reset ${items}, ${item} & ${random) to empty
     items=
@@ -46,18 +46,18 @@ if [ ${#cmnd_aliases[@]} -gt 0 ]; then
     cp ${file} ${name}
 
     # Add an alias so we can remove it
-    bogus=$(${sudoadm} -Vf ${name} -aC ${data} "${cmnd_aliases[${data}]}")
+    bogus=$(${sudoadm} -Vf ${name} -aH ${data} "${host_aliases[${data}]}")
     if [ $? -ne 0 ]; then
-      echo "Failed addition of new '${data}' Cmnd_Alias" && exit 1
+      echo "Failed addition of new '${data}' Host_Alias" && exit 1
     fi
 
     # Create a needle to search for
-    needle="^Cmnd_Alias.*${data}.*$(echo "${cmnd_aliases[${data}]}"|sed -e 's|, |.*|g')"
+    needle="^Host_Alias.*${data}.*$(echo "${host_aliases[${data}]}"|sed -e 's|, |.*|g')"
 
     # Use ${needle} to create ${haystack} from ${name}
     haystack=$(grep "${needle}" ${name})
     if [ "${haystack}" == "" ]; then
-      echo "Failed validation of new '${data}' Cmnd_Alias" && exit 1
+      echo "Failed validation of new '${data}' Host_Alias" && exit 1
     fi
 
     # Sleep for .1 seconds to accomodate for race conditions
@@ -66,22 +66,22 @@ if [ ${#cmnd_aliases[@]} -gt 0 ]; then
     # Generate a random number for this iteration
     random=$(( $RANDOM % $(expr ${#items[@]}) ))
 
-    # Generate an array from ${cmnd_aliases[${data}]}
-    IFS=',' read -a items <<< "$(echo "${cmnd_aliases[${data}]}")"
+    # Generate an array from ${host_aliases[${data}]}
+    IFS=',' read -a items <<< "$(echo "${host_aliases[${data}]}")"
 
-    # Randomly pick an element from ${cmnd_aliases[${data}]} to remove
+    # Randomly pick an element from ${host_aliases[${data}]} to remove
     item=$(echo "${items[${random}]}")
 
     # Now remove the alias ${data}
-    bogus=$(${sudoadm} -Vf ${name} -rC ${data} "${item}")
+    bogus=$(${sudoadm} -Vf ${name} -rH ${data} "${item}")
     if [ $? -ne 0 ]; then
-      echo "Failed removal of new '${data}' Cmnd_Alias" && exit 1
+      echo "Failed removal of new '${data}' Host_Alias" && exit 1
     fi
 
     # Use ${item} to create ${haystack} from ${name}
     haystack=$(grep "${item}" ${name})
     if [ "${haystack}" != "" ]; then
-      echo "Failed validation for remvoval of '${data}' Cmnd_Alias" && exit 1
+      echo "Failed validation for remvoval of '${data}' Host_Alias" && exit 1
     fi
 
     # Clean up our working file(s)
