make_change_add() & make_change_remove()
 - Revisions for ${search} creation to accomodate for multiline
   patterns

Tests

 - Recursive random number to element handling for removal of
   stanza elements

diff --git a/test/lib/tests/user-remove-from b/test/lib/tests/user-remove-from
--- a/test/lib/tests/user-remove-from
+++ b/test/lib/tests/user-remove-from
@@ -63,14 +63,19 @@ if [ ${#user_aliases[@]} -gt 0 ]; then
     # Sleep for .1 seconds to accomodate for race conditions
     sleep 1
 
-    # Generate a random number for this iteration
-    random=$(( $RANDOM % $(expr ${#items[@]}) ))
-
     # Generate an array from ${user_aliases[${data}]}
     IFS=',' read -a items <<< "$(echo "${user_aliases[${data}]}")"
 
-    # Randomly pick an element from ${user_aliases[${data}]} to remove
-    item=$(echo "${items[${random}]}")
+    # Generate a random number for this iteration
+    while [[ ${random} == "" ]] || [[ ${random} -gt ${#items[@]} ]]; do
+      random=$(( $RANDOM % ${#items[@]} ))
+      if [[ ${random} -lt ${#items[@]} ]] && [[ ${random} -gt -1 ]]; then
+
+        # Randomly pick an element from ${user_aliases[${data}]} to remove
+        item=$(echo "${items[${random}]}")
+        break
+      fi
+    done
 
     # Now remove the alias ${data}
     bogus=$(${sudoadm} -Vf ${name} -rA ${data} "${item}")
@@ -81,7 +86,7 @@ if [ ${#user_aliases[@]} -gt 0 ]; then
     # Use ${item} to create ${haystack} from ${name}
     haystack=$(grep "${item}" ${name})
     if [ "${haystack}" != "" ]; then
-      echo "Failed validation for remvoval of '${data}' User_Alias" && exit 1
+      echo "Failed validation for remvoval of '${item}' from the '${data}' User_Alias" && exit 1
     fi
 
     # Clean up our working file(s)
